version: "3.4"

services:
  postgres_fira:
    ports:
      - "${FIRA_DATABASE_PUBLIC_PORT}:5432"

  keycloak:
    ports:
      - "${KEYCLOAK_PUBLIC_PORT}:8080"

  pgadmin:
    build: pgadmin/.
    ports:
      - "${PGADMIN_PUBLIC_PORT}:80"
    networks:
      - backend
    volumes:
      - pgadmin-volume:/var/lib/pgadmin
    depends_on:
      - postgres_fira
    environment:
      - PGADMIN_DEFAULT_EMAIL=${ADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${ADMIN_PASSWORD}
      - PGADMIN_SERVER_JSON_FILE=~/servers.json

networks:
  backend:

volumes:
  pgadmin-volume:
