version: '3'

services:
  postgres_fira:
    ports:
      - '${FIRA_DATABASE_PUBLIC_PORT}:5432'
    volumes:
      - postgres-fira-volume:/var/lib/postgresql/data

  keycloak:
    ports:
      - '${KEYCLOAK_PUBLIC_PORT}:8080'

  postgres_keycloak:
    volumes:
      - postgres-keycloak-volume:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - '${PGADMIN_PUBLIC_PORT}:80'
    networks:
      - backend
    volumes:
      - pgadmin-volume:/var/lib/pgadmin
    depends_on:
      - postgres_fira
      - postgres_keycloak
    environment:
      - PGADMIN_DEFAULT_EMAIL=${ADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${ADMIN_PASSWORD}

networks:
  backend:

volumes:
  pgadmin-volume:
  postgres-fira-volume:
    driver: local
  postgres-keycloak-volume:
    driver: local
