version: '3'

services:

  fira-be:
    build: fira-be/.
    ports:
      - "${FIRA_BE_PUBLIC_PORT}:80"
    networks: 
      - backend
    depends_on:
      - keycloak
    environment:
      - DB_ADDR=postgres_fira
      - DB_NAME=${FIRA_DB}
      - DB_USER=${FIRA_DB_USER}
      - DB_PASSWORD=${FIRA_DB_PASSWORD}
      - KEYCLOAK_ADMIN_USER=${ADMIN_USER}
      - KEYCLOAK_ADMIN_PASSWORD=${ADMIN_PASSWORD}
    
  postgres_fira:
    image: postgres:12
    networks: 
      - backend
    volumes: 
      - postgres-fira-volume:/var/lib/postgresql/data
    environment: 
      - POSTGRES_DB=${FIRA_DB}
      - POSTGRES_USER=${FIRA_DB_USER}
      - POSTGRES_PASSWORD=${FIRA_DB_PASSWORD}

  keycloak:
    build: keycloak/.
    networks: 
      - backend
    depends_on: 
      - postgres_keycloak
    environment:
      - KEYCLOAK_ADMIN_USER=${ADMIN_USER}
      - KEYCLOAK_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - DB_VENDOR=postgres
      - DB_ADDR=postgres_keycloak
      - DB_USER=${KEYCLOAK_DB_USER}
      - DB_PASSWORD=${KEYCLOAK_DB_PASSWORD}

  postgres_keycloak:
    image: postgres:12
    networks: 
      - backend
    volumes: 
      - postgres-keycloak-volume:/var/lib/postgresql/data
    environment: 
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=${KEYCLOAK_DB_USER}
      - POSTGRES_PASSWORD=${KEYCLOAK_DB_PASSWORD}

networks: 
  backend:

volumes:
  postgres-fira-volume:
    driver: local
  postgres-keycloak-volume:
    driver: local
