version: '3.4'

services:
  fira-be:
    build:
      context: fira/.
      args:
        - FIRA_HOMEPAGE=${FIRA_HOMEPAGE}
    ports:
      - '${FIRA_BE_PUBLIC_PORT}:80'
    networks:
      - backend
    depends_on:
      - keycloak
      - postgres_fira
    restart: unless-stopped
    environment:
      - DB_ADDR=postgres_fira
      - DB_USER=${FIRA_DB_USER}
      - DB_PASSWORD=${FIRA_DB_PASSWORD}
      - KEYCLOAK_HOST_BASE=keycloak:8080
      - KEYCLOAK_ADMIN_USER=${ADMIN_USER}
      - KEYCLOAK_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - FIRA_HOMEPAGE=${FIRA_HOMEPAGE}
    volumes:
      - ${FIRA_BE_DATA_DIRECTORY}:/usr/src/app/data

  postgres_fira:
    image: postgres:12
    networks:
      - backend
    volumes:
      - ${FIRA_BE_DATABASE_DIRECTORY}:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=fira
      - POSTGRES_USER=${FIRA_DB_USER}
      - POSTGRES_PASSWORD=${FIRA_DB_PASSWORD}

  keycloak:
    build: keycloak/.
    networks:
      - backend
    depends_on:
      - postgres_keycloak
    environment:
      - KEYCLOAK_ADMIN_USER=${ADMIN_USER}
      - KEYCLOAK_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - DB_VENDOR=postgres
      - DB_ADDR=postgres_keycloak
      - DB_USER=${KEYCLOAK_DB_USER}
      - DB_PASSWORD=${KEYCLOAK_DB_PASSWORD}

  postgres_keycloak:
    image: postgres:12
    networks:
      - backend
    volumes:
      - ${KEYCLOAK_DATABASE_DIRECTORY}:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=${KEYCLOAK_DB_USER}
      - POSTGRES_PASSWORD=${KEYCLOAK_DB_PASSWORD}

networks:
  backend:
