version: "3.8"

services:
  fira_appsvc:
    build:
      context: fira/.
      args:
        - FIRA_HOMEPAGE=${FIRA_HOMEPAGE}
    ports:
      - "${FIRA_APPSVC_PUBLIC_PORT}:80"
    networks:
      - backend
    depends_on:
      - keycloak
      - postgres_fira
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - FIRA_HOMEPAGE=${FIRA_HOMEPAGE}
      - FIRA_PERSISTENT_DB_HOST=${FIRA_PERSISTENT_DB_HOST}
      - FIRA_PERSISTENT_DB_PORT=${FIRA_PERSISTENT_DB_PORT}
      - FIRA_PERSISTENT_DB_USER=${FIRA_PERSISTENT_DB_USER}
      - FIRA_PERSISTENT_DB_PASSWORD=${FIRA_PERSISTENT_DB_PASSWORD}
      - FIRA_PERSISTENT_DB_DATABASENAME=${FIRA_PERSISTENT_DB_DATABASENAME}
      - KEYCLOAK_HOST_BASE=keycloak:8080
      - KEYCLOAK_ADMIN_USER=${ADMIN_USER}
      - KEYCLOAK_ADMIN_PASSWORD=${ADMIN_PASSWORD}
    volumes:
      - ${FIRA_APPSVC_DATA_DIRECTORY}:/app/fira-appsvc/data

  postgres_fira:
    image: postgres:12
    networks:
      - backend
    volumes:
      - ${FIRA_PERSISTENT_DB_DIRECTORY}:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${FIRA_PERSISTENT_DB_DATABASENAME}
      - POSTGRES_USER=${FIRA_PERSISTENT_DB_USER}
      - POSTGRES_PASSWORD=${FIRA_PERSISTENT_DB_PASSWORD}

  keycloak:
    build: keycloak/.
    networks:
      - backend
    depends_on:
      - postgres_keycloak
    environment:
      - KEYCLOAK_ADMIN_USER=${ADMIN_USER}
      - KEYCLOAK_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - DB_VENDOR=postgres
      - DB_ADDR=postgres_keycloak
      - DB_USER=${KEYCLOAK_DB_USER}
      - DB_PASSWORD=${KEYCLOAK_DB_PASSWORD}

  postgres_keycloak:
    image: postgres:12
    networks:
      - backend
    volumes:
      - ${KEYCLOAK_DATABASE_DIRECTORY}:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=${KEYCLOAK_DB_USER}
      - POSTGRES_PASSWORD=${KEYCLOAK_DB_PASSWORD}

networks:
  backend:
