version: "3.8"

services:
  fira_appsvc:
    environment:
      - NODE_ENV=development

  postgres_fira:
    command: ["postgres", "-c", "log_statement=all", "-c", "log_duration=on"]
    ports:
      - "${FIRA_DEV_PERSISTENT_DB_PUBLIC_PORT}:5432"

  keycloak:
    ports:
      - "${KEYCLOAK_PUBLIC_PORT}:8080"

  pgadmin:
    build: pgadmin/.
    ports:
      - "${PGADMIN_PUBLIC_PORT}:80"
    networks:
      - backend
    volumes:
      - pgadmin-volume:/var/lib/pgadmin
    depends_on:
      - postgres_fira
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
      - PGADMIN_SERVER_JSON_FILE=~/servers.json

networks:
  backend:

volumes:
  pgadmin-volume:
